presubmits:
  - name: test-credstash-operator
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    max_concurrency: 1
    trigger: "(?m)test( please)?"
    run_if_changed: ".*.go"
    rerun_command: "test"
    spec:
      containers:
        - name: "test"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/go-builder:1.14.2
          command:
            - make
          args:
            - test
  - name: lint-credstash-operator
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    max_concurrency: 1
    trigger: "(?m)lint( please)?"
    run_if_changed: ".*.go"
    rerun_command: "lint"
    spec:
      containers:
        - name: "lint"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/go-builder:1.14.2
          command:
            - make
          args:
            - lint
          resources:
            requests:
              memory: "2Gi"
              cpu: 1
  - name: helm-chart-lint
    context: helm-chart-lint
    decorate: true
    run_if_changed: 'deploy/helm/'
    always_run: false
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    max_concurrency: 1
    trigger: "(?m)helm-lint( please)?"
    rerun_command: "helm-lint"
    spec:
      containers:
        - name: "helm-chart-lint"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/helm:v3.1.1
          command:
            - make
          args:
            - helm-lint
  - name: helm-chart-validate
    context: helm-chart-validate
    decorate: true
    run_if_changed: 'deploy/helm/'
    always_run: false
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    max_concurrency: 1
    trigger: "(?m)helm-validate( please)?"
    rerun_command: "helm-validate"
    spec:
      containers:
        - name: "helm-chart-validate"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/helm:v3.1.1
          command:
            - make
          args:
            - helm-validate
  - name: helm-chart-package
    context: helm-chart-package
    decorate: true
    run_if_changed: 'deploy/helm/'
    always_run: false
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    max_concurrency: 1
    trigger: "(?m)helm-package( please)?"
    rerun_command: "helm-package"
    spec:
      containers:
        - name: "helm-chart-package"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/helm:v3.1.1
          command:
            - make
          args:
            - helm-package
            - VERSION=0.0.0
  - name: test-semrelease-dryrun
    context: test-semrelease-dryrun
    decorate: true
    always_run: true
    skip_report: false
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    max_concurrency: 1
    labels:
      preset-semantic-release: "true"
      preset-ouzi-helm-push: "true"
    trigger: "(?m)semrelease-dryrun( please)?"
    rerun_command: "semrelease-dryrun"
    spec:
      containers:
        - name: "test-semrelease-dryrun"
          imagePullPolicy: IfNotPresent
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - semantic-release-dry-run
postsubmits:
  - name: credstash-operator-release
    labels:
      preset-semantic-release: "true"
      preset-gcloud-testinfra-prow: "true"
      preset-ouzi-helm-push: "true"
    clone_uri: "git@github.com:ouzi-dev/credstash-operator.git"
    decorate: true
    max_concurrency: 1
    branches:
      - master
    spec:
      containers:
        - name: "release"
          imagePullPolicy: Always
          image: quay.io/ouzi/toolbox:0.1.17
          command:
            - make
          args:
            - init-gcloud-cli
            - semantic-release