{{- if .Values.awsCredentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credstash-operator.credentialsSecretName" . }}
  labels:
    {{- include "credstash-operator.labels" . | nindent 4 }}
  {{- with .Values.awsCredentials.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.awsCredentials.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsCredentials.awsSecretAccessKey | b64enc }}
  AWS_REGION: {{ .Values.awsCredentials.awsRegion | b64enc }}
{{- end -}}