apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "credstash-operator.fullname" . }}
  labels:
    {{- include "credstash-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "credstash-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "credstash-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "credstash-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          envFrom:
          - secretRef:
              name: {{ include "credstash-operator.credentialsSecretName" . }}
          env:
{{- if .Values.namespaceToWatch }}
          - name: WATCH_NAMESPACE
            value: {{ .Values.namespaceToWatch }}
{{- end }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "credstash-operator"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
