// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ouzi-dev/credstash-operator/pkg/credstash (interfaces: SecretGetter)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/ouzi-dev/credstash-operator/pkg/apis/credstash/v1alpha1"
	reflect "reflect"
)

// MockSecretGetter is a mock of SecretGetter interface
type MockSecretGetter struct {
	ctrl     *gomock.Controller
	recorder *MockSecretGetterMockRecorder
}

// MockSecretGetterMockRecorder is the mock recorder for MockSecretGetter
type MockSecretGetterMockRecorder struct {
	mock *MockSecretGetter
}

// NewMockSecretGetter creates a new mock instance
func NewMockSecretGetter(ctrl *gomock.Controller) *MockSecretGetter {
	mock := &MockSecretGetter{ctrl: ctrl}
	mock.recorder = &MockSecretGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSecretGetter) EXPECT() *MockSecretGetterMockRecorder {
	return m.recorder
}

// GetCredstashSecretsForCredstashSecret mocks base method
func (m *MockSecretGetter) GetCredstashSecretsForCredstashSecret(arg0 *v1alpha1.CredstashSecret) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredstashSecretsForCredstashSecret", arg0)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredstashSecretsForCredstashSecret indicates an expected call of GetCredstashSecretsForCredstashSecret
func (mr *MockSecretGetterMockRecorder) GetCredstashSecretsForCredstashSecret(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredstashSecretsForCredstashSecret", reflect.TypeOf((*MockSecretGetter)(nil).GetCredstashSecretsForCredstashSecret), arg0)
}
